version: '3.9'
services:
  service1:
    build:
      context: ./service_1
    ports:
      - "8081:80"
    networks:
      - service1-net

  service2:
    build:
      context: ./service_2
    ports:
      - "8082:80"
    networks:
      - service2-net

networks:
  service1-net:
  service2-net:
